services:
  anyvlm_test_db:
    image: postgres:17
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - 127.0.0.1:5436:5432
    environment:
      - POSTGRES_DB=anyvlm_test
      - POSTGRES_USER=anyvlm_test
      - POSTGRES_PASSWORD=anyvlm-test-pw

  anyvar_test_db:
    image: postgres:17
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - 127.0.0.1:5437:5432
    environment:
      - POSTGRES_DB=anyvar_test
      - POSTGRES_USER=anyvar_test
      - POSTGRES_PASSWORD=anyvar-test-pw

  seqrepo:
    image: biocommons/seqrepo:2024-12-20
    volumes:
      - seqrepo_vol:/usr/local/share/seqrepo

  seqrepo-rest-service:
    # Test: curl http://localhost:5000/seqrepo/1/sequence/refseq:NM_000551.3
    image: biocommons/seqrepo-rest-service:0.2.2
    volumes:
      - seqrepo_vol:/usr/local/share/seqrepo
    depends_on:
      - seqrepo
    command: seqrepo-rest-service -w /usr/local/share/seqrepo/2024-12-20
    network_mode: bridge
    ports:
      - 5000:5000

volumes:
  seqrepo_vol:
    external: true
